### ISSUE TITLE
Preview image does not work in Messenger

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#34]
When I send a link to https://powsummit.com in Signal, the thumbnail image expands as expected.
Same in Discord.
Same in Telegram.
Same in Twitter.

But it does not work in Messenger.

Any ideas?  Are other platforms not working too?

**Comment by gd8097019** [comment]
Hey @bobsummerwill I invested some time for this issue. Metadata's look like okay.
Facebook changes it "display link image policy" depend on countries. I saw a article about that: 
https://www.mysk.blog/2021/02/08/fb-link-previews/

And I saw some Reddit thread to complain for that: 
https://www.reddit.com/r/facebook/comments/kagpzq/messenger_and_messengercom_no_longer_load_link/

In my country also I cannot display image
<img width="626" alt="Screenshot 2023-05-17 at 15 15 55" src="https://github.com/POWSummit/pow-summit-website/assets/102132498/3cc8a0d0-00ea-4ace-880c-2865bd24267d">

I have a digitalocean server. I connected that as VPN and it worked: 
<img width="620" alt="Screenshot 2023-05-17 at 15 15 47" src="https://github.com/POWSummit/pow-summit-website/assets/102132498/d6377ec0-1acb-4828-8d10-e73cc04efc05">

I think we cannot solve this issue because it is depend on Facebook

**Comment by bobsummerwill** [comment]
What a stupid thing.  Well it is happening to me in Canada too, but I agree -  closing the issue.
