### ISSUE TITLE
Jay - Use the Litecoin Foundation logo everywhere else

### ISSUE THREAD

**Issue by bobsummerwill** [POWSummit/pow-summit-website#4]
Bob will try to dig up source graphics for the LTC Foundation logo and share them in the Telegram group chat.

**Comment by bobsummerwill** [comment]
https://www.litecoin.net/litecoin-foundation#resources

Or here they are in a dropbox link: https://www.dropbox.com/sh/rbbme72r2er4t2x/AAAHw16O0yVdkdLFBjFugEh8a?dl=0

**Comment by gd8097019** [comment]
Icon updates

Note: Mistakenly I made commit to main repository. Next time I will create pull request from my forked repo.

**Comment by bobsummerwill** [comment]
So we've only got the logos left in one place - and the bottom.

But the LTC one needs to use the "LTC Foundation" one, not the Litecoin one.

See Telegram group where @BugattiLira dropped the images for that.

**Comment by gd8097019** [comment]
I changed LTC logo with LTC Foundation but because of it's only transparent it looks like a bit weird. 
I made white background with CSS if it is okay for you can continue with that. Otherwise I need to logo file with "L" with white background. 

I will show both screenshoot: 

Using given .svg and without background: 

<img width="789" alt="Screenshot 2023-02-24 at 11 00 00" src="https://user-images.githubusercontent.com/102132498/221124504-820e39ba-f63c-455c-abc5-35b1dd7bdf0f.png">

Addin white background and some radius: 

<img width="728" alt="Screenshot 2023-02-24 at 10 54 05" src="https://user-images.githubusercontent.com/102132498/221124605-1a281361-97fe-43b3-8876-7c48dc49d60b.png">

I this PR for background version: https://github.com/POWSummit/pow-summit-website/pull/11

**Comment by bobsummerwill** [comment]
@BugattiLira Please could you make a call on this?  Thanks!

**Comment by bobsummerwill** [comment]
Merged #11
